package simpol.tokens;

public enum TokenType {
	ID, OPEN_BLOCK, CLOSE_BLOCK, INT_CONST, STG_CONST, BLN_CONST, BLN_KWORD, STG_KWORD, INT_KWORD, VARIABLE_KWORD, CODE_KWORD, PUT_KWORD, ASK_KWORD, IN_KWORD, PRT_KWORD, ADD_KWORD, SUB_KWORD, MUL_KWORD, DIV_KWORD, MOD_KWORD, GRT_KWORD, GRE_KWORD, LET_KWORD, LEE_KWORD, EQL_KWORD, AND_KWORD, OHR_KWORD, NON_KWORD,

	END;

}
